---
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2ExMWUxMjEwMDRlNGU3ZDUxMWY4MjEwNGYzMDY4%0ANjYxY2NmYSIsInNpZyI6ImRUWDZ0ejVOd0lRNlhvWWE2S0V3RFRUdHhvST0i%0AfQ==%0A
  sha: 4e1338497b8da50b84307191bb3418e9ec5715d7
  size: 1551070
ruby/ruby-1.9.2-p180.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2EyMWUxMjEwMDRlNGU3ZDUxMWY1NTMwNGYzMDY5%0AMGM4OGZkOSIsInNpZyI6IkE1VlllWVduMVpadFNHbGRpeGM1STgzTU9Jaz0i%0AfQ==%0A
  sha: 6a482bc07239b37bcadf68dda63c65d20dc19ebe
  size: 11158935
mysql/client-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2EyMWUxMjIyMDRlNGU5ODYzOTI2YjEwNGZiNjhi%0AMjU5YzlmYyIsInNpZyI6IjB6L0lDc3pQNXY1c05lcUwvSVBFaW1VVTcxMD0i%0AfQ==%0A
  sha: 6e5a17195831688a5f14f20aa5d9cd5d5f4164db
  size: 4105211
ruby/rubygems-1.8.24.tgz:
  object_id: eyJzaWciOiJkZkdFQ2k0aXFua1pESmZvalNKa09tSGtySkU9Iiwib2lkIjoi%0ANGU0ZTc4YmNhNDFlMTIyMjA0ZTRlOTg2M2QwNzYzMDRmYTFjYzI4Nzk3YTki%0AfQ==%0A
  sha: 30f27047e74f7943117736a0d3e224994fee0905
  size: 380101
ruby/bundler-1.2.1.gem:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2EzMWUxMjEyMDRlNGU4NmVlMzk2OTIwNTBhMTYy%0ANTJmMDUyZiIsInNpZyI6InZYOFl0dktMN3k5NWNHWTZnbnpVcFpHY2tUMD0i%0AfQ==%0A
  sha: 0cbe6ad7a41f064d6c11c1058465fffb1bd58069
  size: 226816
mysql/client-5.5.29-rel29.4-401.Linux.x86_64.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E0MWUxMjEwMDRlNGU3ZDUxNzYxOGYwNTEwYjIx%0AZDI4YTJiYiIsInNpZyI6InJocVhmTUFMZEpTbHNERG5OTWczZVJOenlCWT0i%0AfQ==%0A
  sha: 8dad5b2d9fee7b0a98e419949c6f7d94c39443f2
  size: 4564276
libyaml/yaml-0.1.4.tgz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E1MWUxMjIwMDRlNGU4ZWM2ODQwNzcwNTExZDM1%0AZmZjOTFiZCIsInNpZyI6IlIwQk51U2ZSTVQ1czgzVHpPQkZBVVFxYjJWaz0i%0AfQ==%0A
  sha: e0e5e09192ab10a607e3da2970db492118f560f2
  size: 471759
ruby/ruby-1.9.3-p392.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E2MWUxMjEyMDRlNGU4NmVlYmU1OTEwNTEzYTMy%0ANzA5NjhmMyIsInNpZyI6IlRXUWlidzkzcDQyVG1STEtnR1dIKzg5UHlqYz0i%0AfQ==%0A
  sha: ec75fcbd3b6b46ce6ec997ee4c86145b4abd5748
  size: 12557294
